collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Hero Image", name: "hero", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "home"
    label: "Homepage"
    delete: false
    files:
      - file: "src/_data/home.yml"
        label: "Homepage Settings"
        name: "settings"
        fields:
          - label: "Popular"
            name: "popular"
            widget: "object"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                summary: "{{fields.title}}"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
                  - { label: "Image", name: "image", widget: "image", required: false }

          - label: "The Foot of the Bed"
            name: "foot_of_bed"
            widget: "object"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                summary: "{{fields.title}} — {{fields.category}}"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: "Category", name: "category", widget: "string", required: false }
                  - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
          - label: "Top Items"
            name: "top"
            widget: "object"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                field:
                  label: "Item"
                  name: "item"
                  widget: "object"
                  fields:
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "URL", name: "url", widget: "string" }
                    - { label: "Image", name: "image", widget: "image", required: false }
                    - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
          - { label: "Latest Count", name: "latest_count", widget: "number", default: 6, min: 1, max: 24 }
